# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: FujidenoloSolutions.SonicDICOM
PackageVersion: 3.17.0
PackageLocale: en-US
Publisher: Fujidenolo Solutions
PublisherUrl: https://fujidenolo-s.co.jp/
PublisherSupportUrl: https://sonicdicom.com/contact-us/
PrivacyUrl: https://fujidenolo-s.co.jp/privacy/en/
Author: Fujidenolo Solutions
PackageName: SonicDICOM PACS
PackageUrl: https://sonicdicom.com/
License: Proprietary
LicenseUrl: https://fujidenolo-s.co.jp/terms/en/
Copyright: © 2013-2025 Fujidenolo Solutions Co., Ltd.
ShortDescription: Web-based medical imaging platform for storage, visualization and sharing. DICOM server + HTML5 DICOM viewer for both on-premises and cloud environments.
Description: |-
  SonicDICOM PACS Web-based medical imaging platform for storage, visualization and sharing.
  DICOM server + HTML5 DICOM viewer for both on-premises and cloud environments.

  Advantages of web-based DICOM Viewer
  - Just access the URL and log in to view images
  - Secure access through HTTPS protocol
  - No additional software installation
  - No plugins/addons required
  - Available on various OSs (Windows, macOS, Linux, iOS, Android)
  - PC / tablet / smartphone are supported
  - Works lightly even on low-spec devices
  - Easy integration with EMR, HIS and RIS via URL
Tags:
- DICOM
- Medical
- PACS
- Server
- Trial
- dcm
ReleaseNotesUrl: https://docs.sonicdicom.com/release-notes/3_17_0.html
PurchaseUrl: 
Documentations:
- DocumentLabel: Starter Guide
  DocumentUrl: https://docs.sonicdicom.com/starter-guide/on-premises/
- DocumentLabel: User Manual
  DocumentUrl: https://docs.sonicdicom.com/user-manual/
- DocumentLabel: Glossary
  DocumentUrl: https://docs.sonicdicom.com/glossary/
ManifestType: defaultLocale
ManifestVersion: 1.10.0
