# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: WingSoft.FTPRush
PackageVersion: 3.5.8
InstallerLocale: en-US
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Protocols:
- ftp
ProductCode: '{933E6450-11BA-417C-AA87-06515B12516F}_is1'
ReleaseDate: 2024-06-24
AppsAndFeaturesEntries:
- DisplayName: FTP Rush 3.5.8
  ProductCode: '{933E6450-11BA-417C-AA87-06515B12516F}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\FTP Rush'
Installers:
- Architecture: x86
  InstallerUrl: https://www.wftpserver.com/download/FTPRush-Setup.exe
  InstallerSha256: 5126BF45E5BF521A25BA05ABA7D5C9B69455C17CECF09F269729685EED8E7409
ManifestType: installer
ManifestVersion: 1.10.0


