# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Transmission.Transmission
PackageVersion: 4.0.6
PackageLocale: en-US
Publisher: Transmission Project
PublisherUrl: https://transmissionbt.com/
PublisherSupportUrl: https://forum.transmissionbt.com/
PackageName: Transmission
PackageUrl: https://transmissionbt.com/
License: GPLv3
LicenseUrl: https://github.com/transmission/transmission/blob/main/COPYING
Copyright: Copyright 2005-2023. All code is copyrighted by the respective authors.
CopyrightUrl: https://github.com/transmission/transmission/blob/main/COPYING
ShortDescription: Transmission is a cross-platform BitTorrent client
Description: |-
  Transmission - A Fast, Easy and Free Bittorrent Client For macOS, Windows and Linux

  Transmission is designed for easy, powerful use. We've set the defaults to just work and it only takes a few clicks to configure advanced features like watch directories, bad peer blocklists, and the web interface. When Ubuntu chose Transmission as its default BitTorrent client, one of the most-cited reasons was its easy learning curve.

  Unlike many cross-platform applications, Transmission integrates seamlessly with your operating system.
  The Qt-based Windows UI has been modernized and is fully Windows 11 ready.
Moniker: transmission
Tags:
- bittorrent
- p2p
- torrent
ReleaseNotes: |-
  Transmission 4.0.6
  This is a bugfix-only release. Everyone's feedback on 4.0.x has been very helpful -- thanks for all the suggestions, bug reports, and pull requests!
  What's New in 4.0.6
  All Platforms
  - Improved parsing HTTP tracker announce response. (#6223)
  - Fixed 4.0.0 bug that caused some user scripts to have an invalid TR_TORRENT_TRACKERS environment variable. (#6434)
  - Fixed 4.0.0 bug where alt-speed-enabled had no effect in settings.json. (#6483)
  - Fixed 4.0.0 bug where the GTK client's "Use authentication" option was not saved between's sessions. (#6514)
  - Fixed 4.0.0 bug where the filename for single-file torrents aren't sanitized. (#6846)
  macOS Client
  - Fix: Sparkle support for handling beta version updates. (#5263)
  - Fixed app unable to start when having many torrents and TimeMachine enabled. (#6523)
  - Fix: Sparkle Version Comparator. (#6623)
  Qt Client
  - Fixed 4.0.0 bug where piece size description text and slider state in torrent creation dialog are not always up-to-date. (#6516)
  GTK Client
  - Fixed build when compiling with GTKMM 4. (#6393)
  - Added developer name to metainfo files. (#6598)
  - Added the launchable desktop-id to metainfo files. (#6779)
  - Fixed build when compiling on BSD. (#6812)
  Web Client
  - Fixed a 4.0.0 bug where the infinite ratio symbol was displayed incorrectly in the WebUI. (#6491, #6500)
  - Fixed layout issue in speed display. (#6570)
  - General UI improvement related to filterbar and fixes download/upload speed info wrap. (#6761)
  Daemon
  - Fixed a couple of logging issues. (#6463)
  Everything Else
  - Updated flatpak release metainfo. (#6357)
  - Fixed libtransmission build on very old cmake versions. (#6418)
  - UTP peer connections follow user-defined speed limits better now. (#6551)
  - Only use a single concurrent queue for timeMachineExclude instead of one queue per torrent (#6523). (#6558)
  - Fixed 4.0.5 bug where svg and png icons in the WebUI might not be displayed. (#6563)
  - Fixed 4.0.0 bug where alt-speed-enabled had no effect in settings.json. (#6564)
  - Fixed 4.0.0 bugs where some RPC methods don't put torrents in recently-active anymore. (#6565)
  - Improved parsing HTTP tracker announce response. (#6567)
  - Fixed compatibility with clang-format 18. (#6690)
  - Fixed build when compiling with mbedtls 3.x . (#6823)
  Thank You!
  Last but certainly not least, a big Thank You to these people who contributed to this release:
  Contributions to All Platforms:
  - @tearfur (Yat Ho):
    - Improved parsing HTTP tracker announce response. (#6223)
    - Fix: add check for EWOULDBLOCK. (#6350)
    - Fixed 4.0.0 bug where alt-speed-enabled had no effect in settings.json. (#6483)
    - Fixed 4.0.0 bug where the GTK client's "Use authentication" option was not saved between's sessions. (#6514)
    - Fixed 4.0.0 bug where the filename for single-file torrents aren't sanitized. (#6846)
  Contributions to macOS Client:
  - @nevack (Dzmitry Neviadomski):
    - Code review. (#5263, #6523)
  - @zorgiepoo (Zorg):
    - Code review. (#5263)
  Contributions to GTK Client:
  - @brad0 (Brad Smith):
    - Fixed build when compiling on BSD. (#6812)
  - @wjt (Will Thompson):
    - Added developer name to metainfo files. (#6598)
    - Added launchable tag to metainfo files. (#6720)
    - Added the launchable desktop-id to metainfo files. (#6779)
  Contributions to Web Client:
  - @Rukario:
    - General UI improvement related to filterbar and fixes download/upload speed info wrap. (#6761)
  - @tearfur (Yat Ho):
    - Code review. (#6570, #6761)
    - Fixed a 4.0.0 bug where the infinite ratio symbol was displayed incorrectly in the WebUI. (#6491, #6500)
  - @tessus (Helmut K. C. Tessarek):
    - Fixed layout issue in speed display. (#6570)
  Contributions to Everything Else:
  - @nevack (Dzmitry Neviadomski):
    - Code review. (#6418)
  - @orangepizza:
    - Fixed build when compiling with mbedtls 3.x . (#6823)
  - @tearfur (Yat Ho):
    - UTP peer connections follow user-defined speed limits better now. (#6551)
    - Fixed 4.0.5 bug where svg and png icons in the WebUI might not be displayed. (#6563)
    - Fixed 4.0.0 bug where alt-speed-enabled had no effect in settings.json. (#6564)
    - Fixed 4.0.0 bugs where some RPC methods don't put torrents in recently-active anymore. (#6565)
    - Fix: add check for EWOULDBLOCK (#6350). (#6566)
    - Improved parsing HTTP tracker announce response. (#6567)
  - @wjt (Will Thompson):
    - Updated flatpak release metainfo. (#6357)
ReleaseNotesUrl: https://github.com/transmission/transmission/releases/tag/4.0.6
Documentations:
- DocumentLabel: Transmission Add-Ons
  DocumentUrl: https://transmissionbt.com/addons
- DocumentLabel: Community Forums
  DocumentUrl: https://forum.transmissionbt.com/
- DocumentLabel: Developer & Contributor Discussions
  DocumentUrl: https://github.com/transmission/transmission/discussions
ManifestType: defaultLocale
ManifestVersion: 1.10.0
