# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Netbird.Netbird
PackageVersion: 0.54.1
PackageLocale: en-US
Publisher: NetBird GmbH
PublisherUrl: https://netbird.io/
PublisherSupportUrl: https://github.com/netbirdio/netbird/issues
PrivacyUrl: https://netbird.io/privacy
Author: Wiretrustee UG (haftungsbeschreankt)
PackageName: Netbird
PackageUrl: https://netbird.io/
License: BSD-3-Clause
LicenseUrl: https://github.com/netbirdio/netbird/blob/HEAD/LICENSE
Copyright: Copyright (c) 2024 Wiretrustee UG (haftungsbeschränkt) & AUTHORS
CopyrightUrl: https://netbird.io/terms
ShortDescription: Connect your devices into a secure WireGuard®-based overlay network with SSO, MFA and granular access controls.
Description: |-
  NetBird combines a configuration-free peer-to-peer private network and a centralized access control system in a single platform, making it easy to create secure private networks for your organization or home.
  Connect. NetBird creates a WireGuard-based overlay network that automatically connects your machines over an encrypted tunnel, leaving behind the hassle of opening ports, complex firewall rules, VPN gateways, and so forth.
  Secure. NetBird enables secure remote access by applying granular access policies while allowing you to manage them intuitively from a single place. Works universally on any infrastructure.
Moniker: netbird
Tags:
- network
- security
- vpn
- wireguard
ReleaseNotes: |-
  What's Changed
  - [client] Eliminate upstream server strings in dns code by @lixmal in https://github.com/netbirdio/netbird/pull/4267
  - [management] use readlock on add peer by @pascal-fischer in https://github.com/netbirdio/netbird/pull/4308
  - [server, relay] Add pprof support for Relay server by @pappz in https://github.com/netbirdio/netbird/pull/4203
  - [client] Create NRPT rules separately per domain by @lixmal in https://github.com/netbirdio/netbird/pull/4329
  - [client] Skip dns upstream servers pointing to our dns server IP to prevent loops by @lixmal in https://github.com/netbirdio/netbird/pull/4330
  - [client] Distinguish between NXDOMAIN and NODATA in the dns forwarder by @lixmal in https://github.com/netbirdio/netbird/pull/4321
  Full Changelog: https://github.com/netbirdio/netbird/compare/v0.54.0...v0.54.1
ReleaseNotesUrl: https://github.com/netbirdio/netbird/releases/tag/v0.54.1
PurchaseUrl: https://netbird.io/pricing
Documentations:
- DocumentLabel: Docs
  DocumentUrl: https://docs.netbird.io/
ManifestType: defaultLocale
ManifestVersion: 1.10.0
