# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: stnkl.EverythingToolbar
PackageVersion: 2.0.4
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
  - PackageIdentifier: voidtools.Everything
ProductCode: '{b5f0ac2d-98da-4392-9d12-78444db9caa9}_is1'
ReleaseDate: 2025-08-30
AppsAndFeaturesEntries:
- ProductCode: '{b5f0ac2d-98da-4392-9d12-78444db9caa9}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\EverythingToolbar'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/srwi/EverythingToolbar/releases/download/2.0.4/EverythingToolbar-2.0.4-x64.exe
  InstallerSha256: 6353B2B4313718D4875F921D88C3DE3F15191F7E9BCBFBC9BF52A02AC214FC55
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.10.0
