# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Oracle.VirtualBox
PackageVersion: 7.1.2
Platform:
- Windows.Desktop
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
  InstallLocation: --msiparams "INSTALLDIR="<INSTALLPATH>""
  Custom: -msiparams REBOOT=ReallySuppress
InstallerSuccessCodes:
- 3010
UpgradeBehavior: install
FileExtensions:
- ova
- ovf
- vdi
- vhd
- vmdk
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2024-09-27
AppsAndFeaturesEntries:
- DisplayName: Oracle VirtualBox 7.1.2
Installers:
- Architecture: x86
  InstallerUrl: https://download.virtualbox.org/virtualbox/7.1.2/VirtualBox-7.1.2-164945-Win.exe
  InstallerSha256: 95BE216F865155F64CF461B712462405E25C600BD92B873D89AC43E8B564C15C
  ProductCode: '{7B20AD7D-86BD-4033-B642-C4F70444EFA1}'
ManifestType: installer
ManifestVersion: 1.10.0
