# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: DesktopPaints.AnimationMaker
PackageVersion: 3.5.42
InstallerType: exe
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /SILENT /ACCEPTLICENSE
UpgradeBehavior: install
FileExtensions:
- asw
- bmp
- jpeg
- png
ReleaseDate: 2025-08-25
Installers:
- Architecture: x86
  InstallerUrl: https://download.animationsoftware7.com/dpa_maker.exe
  InstallerSha256: D8C732A1F8306B1CFF7D8DF2394FB192B5094CE312C3BF1E4F6945E1BBA9B86C
ManifestType: installer
ManifestVersion: 1.10.0
