# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json

PackageIdentifier: DesktopPaints.AnimationMaker
PackageVersion: 3.5.42
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.10.0
