# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: JAMSoftware.SpaceObServer.Client
PackageVersion: 8.3.3
InstallerLocale: en-US
InstallerType: inno
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: SpaceObServer Client_is1
ReleaseDate: 2025-07-30
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  - PackageIdentifier: Microsoft.VCRedist.2013.x64
  - PackageIdentifier: Microsoft.SQLServer.2019.Express
AppsAndFeaturesEntries:
- DisplayName: SpaceObServer Client V8.3.3
  ProductCode: SpaceObServer Client_is1
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\JAM Software\SpaceObServer Client'
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.jam-software.de/spaceobserver/archive/v8.3.3.2255/SpaceObServer-Client-Setup.exe
  InstallerSha256: C273CEF5DE4402E93A0FD2F0047592DFE84C72F65C092ACFD3D1D0B74BC904C8
ManifestType: installer
ManifestVersion: 1.10.0
