# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: PremiumSoft.NavicatMySQL
PackageVersion: 17.3.1
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Navicat 17 for MySQL_is1
ReleaseDate: 2025-08-04
AppsAndFeaturesEntries:
- ProductCode: Navicat 17 for MySQL_is1
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\PremiumSoft\Navicat 17 for MySQL'
Installers:
- Architecture: x64
  Scope: user
  InstallerLocale: en-US
  InstallerUrl: https://download3.navicat.com/download/navicat17_mysql_en_x64.exe
  InstallerSha256: ECB27D6C045EFC94F8E3BF3CBE3629FA0BE5D8E3A116C311866B42340A56B179
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerLocale: en-US
  InstallerUrl: https://download3.navicat.com/download/navicat17_mysql_en_x64.exe
  InstallerSha256: ECB27D6C045EFC94F8E3BF3CBE3629FA0BE5D8E3A116C311866B42340A56B179
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.10.0
