# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Nevercenter.Silo
PackageVersion: 2025.2.0
PackageLocale: en-US
Publisher: Nevercenter
PublisherUrl: https://nevercenter.com/
PublisherSupportUrl: https://nevercenter.com/camerabag/support
Author: Nevercenter
PackageName: Silo
PackageUrl: https://nevercenter.com/silo/
License: Proprietary
Copyright: © Nevercenter 2003-2025
ShortDescription: Silo is a lightweight and lightning-fast 3D polygonal modeler and UV mapper, offering a deep, industry-grade toolset and easy-to-master workflow at an insanely affordable price.
Description: |-
  Silo is a lightweight and lightning-fast 3D polygonal modeler and UV mapper, offering a deep, industry-grade toolset and easy-to-master workflow at an insanely affordable price.
  Its lightweight, focused, and portable nature have made it THE go-to pure modeler for over a decade, either used standalone or as the perfect modeling upgrade for all-in-one tools like Maya or Blender.
  It's ideal for creating base meshes for Mudbox or ZBrush (including GoZ support), and works seamlessly with Unity and Unreal game engines for creating all kinds of 3D game assets.

  Try Silo and Milo free for 7 days! At any point, you can purchase a license to unlock the time restriction and register the programs on your system.
ReleaseNotesUrl: https://nevercenter.com/silo/features/#release_notes
PurchaseUrl: https://www.nevercenter.com/checkout/?utm_source=silopg&utm_term=2_x&utm_campaign=silo_buy
Documentations:
- DocumentLabel: Glen Southern's Silo Fundamentals Series (Beginner)
  DocumentUrl: https://nevercenter.com/silo/tutorials/glen_fundamentals
- DocumentLabel: Silo Tools Series (Beginner)
  DocumentUrl: https://nevercenter.com/silo/tutorials/features_tools
- DocumentLabel: Silo Manual
  DocumentUrl: https://nevercenter.com/silo3d/wiki/index.php?title=Silo_Manual
ManifestType: defaultLocale
ManifestVersion: 1.10.0
