# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: SuperFlexibleSoftware.Syncovery
PackageVersion: 11.7.1
PackageLocale: en-US
Publisher: Super Flexible Software
PublisherUrl: https://www.syncovery.com/
PublisherSupportUrl: https://www.syncovery.com/support/
PrivacyUrl: https://www.syncovery.com/privacy/
Author: Tobias Giesen
PackageName: Syncovery
PackageUrl: https://www.syncovery.com/
License: Proprietary
LicenseUrl: https://www.syncovery.com/license/
Copyright: Copyright by Tobias Giesen
ShortDescription: Syncovery is a powerful file synchronization and backup software. It allows users to sync files between local folders, network drives, and cloud services (such as Google Drive, Dropbox, Amazon S3, and more)
Description: |-
  Syncovery is a powerful file synchronization and backup software. It allows users to sync files between local folders, network drives, and cloud services (such as Google Drive, Dropbox, Amazon S3, and more)
  In today’s digital world, where we store vast amounts of sensitive data on our computers, regular backups are essential. Whether it’s a personal laptop or a work computer, data loss can be devastating. Photos, important documents, work projects, and personal memories can all vanish in an instant. This is where reliable Windows backup and sync software becomes crucial. It safeguards against data loss, legal repercussions, and cyber attacks. A robust backup system provides security and peace of mind. Syncovery stands out with its versatility and user-friendly interface, making it an excellent choice for data protection.
 
  Syncovery is also a highly configurable file synchronization software that can be used with manual or automated transfers for data exchange and for a wide variety of corporate processes.
  
  Here’s a list of the most important capabilities of Syncovery. To get a full impression of the available features, it is recommended to download and try the software and take a direct look at the available options.

  We are proud to say that this is one of the most comprehensive file synchronization tools available.
  - Synchronizes or Backs Up Files
  - Copy several files in parallel
  - Includes a scheduler
  - Internet and Cloud Support
  - Compression and Encryption Support
  - Detects Moved Files
  - SmartTracking
  - Exact Mirror Mode
  - Unattended Mode
  - Copy Locked Files
  - Versioning
  - Block Level Copying
  - Database-safe mode
  - Can Use Recycle Bin
  - File Masks & Filters
  - Daylight Saving Time / Time Zones
  - Easy Resuming On Disk Full
  - Obsolete File Folders

  You will automatically receive a 30-day trial version – registration is not necessary
Tags:
- backup
- migration
- sync
- Trial
ReleaseNotesUrl: https://www.syncovery.com/detailed-version-history/
PurchaseUrl: https://www.syncovery.com/purchase/
Documentations:
- DocumentLabel: Documentation
  DocumentUrl: https://www.syncovery.com/category/documentation/
- DocumentLabel: Forum
  DocumentUrl: https://www.syncovery.com/forum/
ManifestType: defaultLocale
ManifestVersion: 1.10.0
