# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: SuperFlexibleSoftware.Syncovery
PackageVersion: 11.7.1
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2025-08-17
ElevationRequirement: elevatesSelf
Installers:
- InstallerLocale: fr-FR
  Architecture: x86
  InstallerUrl: https://www.syncovery.com/release/SyncoverySetupFR.exe
  InstallerSha256: D11DE4005EA55F86440A85774DB6185AAE1BF7327839BDFEE9DB6A10A966C0E7
  ProductCode: Syncovery_is1
- InstallerLocale: fr-FR
  Architecture: x64
  InstallerUrl: https://www.syncovery.com/release/Syncovery64SetupFR.exe
  InstallerSha256: C77D7667CF6837A54615B998AA145CE01B5C63DC7AD4B6E8CDEB6CD5BB6467CE
  ProductCode: Syncovery x64_is1
- InstallerLocale: en-US
  Architecture: x86
  InstallerUrl: https://www.syncovery.com/release/SyncoverySetup.exe
  InstallerSha256: 19B8D08D2423FA8D36805F275C50C3A7DA1DE7D009546D4D910C416BF66518B2
  ProductCode: Syncovery_is1
- InstallerLocale: en-US
  Architecture: x64
  InstallerUrl: https://www.syncovery.com/release/Syncovery64Setup.exe
  InstallerSha256: E448D55AF296C8DF2F6A25D6B467FB5D9DBEA7B5D54EAD5AFC2424F739E12039
  ProductCode: Syncovery x64_is1
- InstallerLocale: de-DE
  Architecture: x86
  InstallerUrl: https://www.syncovery.com/release/SyncoverySetupDE.exe
  InstallerSha256: 4BB64C69775E6541E95B7AE91224CC1D44E1AB36EADCF0E70C71AE50F614D99B
  ProductCode: Syncovery_is1
- InstallerLocale: de-DE
  Architecture: x64
  InstallerUrl: https://www.syncovery.com/release/Syncovery64SetupDE.exe
  InstallerSha256: 5DC16407EA3E9B18BCE45AD8DB5ED77D4C15F4263B928BF4D67A9677117CBD6C
  ProductCode: Syncovery x64_is1
ManifestType: installer
ManifestVersion: 1.10.0
