# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: CoralCreek.SQLiteExpert
PackageVersion: 5.5.37.648
InstallerLocale: en-US
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2025-08-01
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\SQLite Expert\Personal 5'
Installers:
- Architecture: x86
  InstallerUrl: https://www.sqliteexpert.com/v5/SQLiteExpertPersSetup32.exe
  InstallerSha256: 7935E99092B94F21831AAF2FDD260C4B24432037053EEF44B4C5BAABA2E98770
  ProductCode: SQLite Expert Personal 5 - 32bit_is1
  AppsAndFeaturesEntries:
  - ProductCode: SQLite Expert Personal 5 - 32bit_is1
- Architecture: x64
  InstallerUrl: https://www.sqliteexpert.com/v5/SQLiteExpertPersSetup64.exe
  InstallerSha256: D572B823FEB351D0A5D99F8C8B7092F536B49A7476269B96B06C2F148C160C37
  ProductCode: SQLite Expert Personal 5 - 64bit_is1
  AppsAndFeaturesEntries:
  - ProductCode: SQLite Expert Personal 5 - 64bit_is1
ManifestType: installer
ManifestVersion: 1.10.0
