# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: COMPELSONLaboratories.CDD.Full
PackageVersion: 1.0.16.0
InstallerLocale: en-US
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{3DCF00F5-04A5-4543-A088-70548081120E}_is1'
ReleaseDate: 2022-07-28
AppsAndFeaturesEntries:
- Publisher: COMPELSON Labs
  ProductCode: '{3DCF00F5-04A5-4543-A088-70548081120E}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Compiled Driver Disc (Full)'
Installers:
- Architecture: x86
  InstallerUrl: https://download.mobiledit.com/drivers/setup_cdd_complete_1_0_16_0.exe
  InstallerSha256: 8985140CF1301E85FEDE6643DDDD94225F16903BDE12EFAEFEB5F5071C76484A
ManifestType: installer
ManifestVersion: 1.10.0
