# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: JAMSoftware.SpaceObServer
PackageVersion: 8.3.3
PackageLocale: en-US
Publisher: JAM Software
PublisherUrl: https://www.jam-software.com/
PublisherSupportUrl: https://www.jam-software.com/support.shtml
PrivacyUrl: https://www.jam-software.com/company/privacy.shtml
Author: JAM Software
PackageName: SpaceObServer
PackageUrl: https://www.jam-software.com/spaceobserver
License: Proprietary
LicenseUrl: https://www.jam-software.com/company/license_agreement.shtml
Copyright: © 1996-2025 by Joachim Marder e.K.
CopyrightUrl: https://www.jam-software.com/company/license_agreement.shtml
ShortDescription: Bring order and security to your storage in three steps!
Description: |-
  SpaceObServer is an enterprise-grade storage management and analysis tool for Windows that continuously monitors disk usage across servers (local/network/cloud), archives file-level data in a SQL database, and automates reporting/compliance to optimize storage efficiency

  Key Features:
  - Continuous Scanning: Tracks storage changes in real-time via a background Scan Service, storing metadata in a SQL database for instant historical analysis and trend visualization.
  - Multi-Platform Support: Scans Windows/Linux servers, Exchange mailboxes, SharePoint, Amazon S3, Azure Blob Storage, and network drives.
  - Compliance & Security: Enforces RBAC (Role-Based Access Control), audits permissions, and ensures GDPR compliance with on-premises data processing.
  - Automation: Schedules scans, identifies redundant/old files, and triggers cleanup (e.g., deduplication via NTFS hardlinks).
  - Advanced Reporting: Generates exportable reports (PDF, Excel, HTML) and dashboards showing storage growth, file aging, and access patterns.
  - Web & Remote Access: Offers browser-based access (Web Access) and remote clients for administrators
Tags:
- Trial
ReleaseNotesUrl: https://www.jam-software.com/spaceobserver/changes.shtml
PurchaseUrl: https://customers.jam-software.de/prices.php?language=EN&article_group_id=8
Documentations:
- DocumentLabel: SpaceObServer Resources
  DocumentUrl: https://www.jam-software.com/spaceobserver/resources.shtml
- DocumentLabel: Online Manual
  DocumentUrl: https://manuals.jam-software.com/spaceobserver/EN/
ManifestType: defaultLocale
ManifestVersion: 1.10.0
