# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: DesktopPaints.AnimationMaker
PackageVersion: 3.5.41
InstallerType: exe
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /silent
UpgradeBehavior: install
FileExtensions:
- asw
- bmp
- jpeg
- png
ReleaseDate: 2025-07-15
Installers:
- Architecture: x86
  InstallerUrl: https://download.animationsoftware7.com/dpa_maker.exe
  InstallerSha256: A06F3FB262D13F1E158302FE35ADB7EFAD001C914ECE8D4FDEB77C500CD43B0C
ManifestType: installer
ManifestVersion: 1.10.0
