# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: HP.HPImageDiags
PackageVersion: 5.0.0.25
InstallerType: portable
Commands:
- ImageDiags
ReleaseDate: 2025-08-25
Installers:
- Architecture: x64
  InstallerUrl: https://ftp.hp.com/pub/idr/ImageDiags5/ImageDiags.exe
  InstallerSha256: 877E50C2EC58956CF365A74062DF461BA6868FE9AB44FB9E69C0BFB5743D733A
ManifestType: installer
ManifestVersion: 1.10.0
