# Created with YamlCreate.ps1 v2.4.3 $debug=AUSU.CRLF.7-4-6.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Oracle.VirtualBox
PackageVersion: 7.1.0
Platform:
- Windows.Desktop
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
  InstallLocation: --msiparams "INSTALLDIR="<INSTALLPATH>""
  Custom: -msiparams REBOOT=ReallySuppress
InstallerSuccessCodes:
- 3010
UpgradeBehavior: uninstallPrevious
FileExtensions:
- ova
- ovf
- vdi
- vhd
- vmdk
AppsAndFeaturesEntries:
- DisplayName: Oracle VirtualBox 7.1.0
Installers:
- Architecture: x86
  InstallerUrl: https://download.virtualbox.org/virtualbox/7.1.0/VirtualBox-7.1.0-164728-Win.exe
  InstallerSha256: BC22F01478B51D4852D6A83318ED682CEE4D89FC9D8EB51B41988A67B04E7DE1
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
- Architecture: x64
  InstallerUrl: https://download.virtualbox.org/virtualbox/7.1.0/VirtualBox-7.1.0-164728-Win.exe
  InstallerSha256: BC22F01478B51D4852D6A83318ED682CEE4D89FC9D8EB51B41988A67B04E7DE1
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ManifestType: installer
ManifestVersion: 1.9.0
